[project]
name = "repo-score"
version = "0.1.0"
description = "Provides a score for a GitHub repository based on various metrics."
readme = "README.md"
requires-python = ">=3.10.4"
dependencies = [
    "pyfiglet>=1.0.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "ruff>=0.9.7",
]
